server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://employee-service:8081
          predicates:
            - Path=/employees/**

        - id: department-service
          uri: http://department-service:8082
          predicates:
            - Path=/departments/**