server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: http://employee:8081
          predicates:
            - Path=/employees/**

        - id: department
          uri: http://department:8082
          predicates:
            - Path=/departments/**